#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [[ -z "$COMMIT_SOURCE" || "$COMMIT_SOURCE" == "message" ]]
then
    ref=$(git rev-parse --abbrev-ref HEAD)
    if [[ $ref =~ ^.*((CLN|PT|NTG)-[0-9]{1,5}).* ]]
    then
        hint=$(cat "$COMMIT_MSG_FILE")
        ticket="${BASH_REMATCH[1]}"
        echo "[${ticket}] " > "$COMMIT_MSG_FILE"
        echo "$hint" >> "$COMMIT_MSG_FILE"
    fi
fi
